#!/usr/bin/env bash

set -e
set -o pipefail

[ -z "$WORKSPACE" ] && WORKSPACE=`pwd`

IMAGE_NAME="bff-build"

docker build -t $IMAGE_NAME -f docker/Dockerfile .
docker run --rm \
           $IMAGE_NAME \
           npm $@
